### ISSUE TITLE
The nginx base image look for config in conf.d not in site-availables

### ISSUE THREAD

**Issue by achretien** [jamessharp/docker-nginx-https-redirect#6]
The default nginx configuration doesn't works like ubuntu ones.
You have to replace the /etc/nginx/conf.d/default.conf file with your default one.

**Comment by marlinhares** [comment]
Thanks @achretien 
First moment when I tested it did not work and I was confused. Followed your suggestion. Now it works.

@jamessharp please fix the container with above suggestion

**Comment by jamessharp** [comment]
balls - fixed in #7 I hope

Sorry everyone
